# TODO refactor to MVC
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1432, 850)
        self.central_widget = QtWidgets.QWidget(MainWindow)
        self.central_widget.setObjectName("central_widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.central_widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.left_layout = QtWidgets.QVBoxLayout()
        self.left_layout.setObjectName("left_layout")
        self.displays = QtWidgets.QHBoxLayout()
        self.displays.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.displays.setObjectName("displays")
        self.display0 = QtWidgets.QGraphicsView(self.central_widget)
        self.display0.setSizeIncrement(QtCore.QSize(0, 0))
        self.display0.setBaseSize(QtCore.QSize(0, 0))
        self.display0.setObjectName("display0")
        self.displays.addWidget(self.display0)
        self.display1 = QtWidgets.QGraphicsView(self.central_widget)
        self.display1.setSizeIncrement(QtCore.QSize(0, 0))
        self.display1.setBaseSize(QtCore.QSize(0, 0))
        self.display1.setObjectName("display1")
        self.displays.addWidget(self.display1)
        self.left_layout.addLayout(self.displays)
        self.cameras = QtWidgets.QHBoxLayout()
        self.cameras.setObjectName("cameras")
        self.camera0 = QtWidgets.QPushButton(self.central_widget)
        self.camera0.setObjectName("camera0")
        self.cameras.addWidget(self.camera0)
        self.camera1 = QtWidgets.QPushButton(self.central_widget)
        self.camera1.setObjectName("camera1")
        self.cameras.addWidget(self.camera1)
        self.camera2 = QtWidgets.QPushButton(self.central_widget)
        self.camera2.setObjectName("camera2")
        self.cameras.addWidget(self.camera2)
        self.left_layout.addLayout(self.cameras)
        self.sensor_data = QtWidgets.QTableWidget(self.central_widget)
        self.sensor_data.setAutoScroll(True)
        self.sensor_data.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.sensor_data.setShowGrid(True)
        self.sensor_data.setCornerButtonEnabled(True)
        self.sensor_data.setRowCount(4)
        self.sensor_data.setColumnCount(7)
        self.sensor_data.setObjectName("sensor_data")
        self.sensor_data.horizontalHeader().setVisible(False)
        self.sensor_data.horizontalHeader().setHighlightSections(False)
        self.sensor_data.verticalHeader().setVisible(False)
        self.sensor_data.verticalHeader().setHighlightSections(False)
        self.left_layout.addWidget(self.sensor_data)
        self.messages = QtWidgets.QTextBrowser(self.central_widget)
        self.messages.setObjectName("messages")
        self.left_layout.addWidget(self.messages)
        self.horizontalLayout.addLayout(self.left_layout)
        self.right_layout = QtWidgets.QVBoxLayout()
        self.right_layout.setObjectName("right_layout")
        self.mode_selection = QtWidgets.QHBoxLayout()
        self.mode_selection.setObjectName("mode_selection")
        self.load_default_button = QtWidgets.QPushButton(self.central_widget)
        self.load_default_button.setObjectName("load_default_button")
        self.mode_selection.addWidget(self.load_default_button)
        self.is_auto_checkbox = QtWidgets.QCheckBox(self.central_widget)
        self.is_auto_checkbox.setObjectName("is_auto_checkbox")
        self.mode_selection.addWidget(self.is_auto_checkbox)
        self.right_layout.addLayout(self.mode_selection)
        self.task_selection = QtWidgets.QVBoxLayout()
        self.task_selection.setObjectName("task_selection")
        self.task0 = QtWidgets.QPushButton(self.central_widget)

        self.task0.setObjectName("task0")
        self.task_selection.addWidget(self.task0)
        self.task1 = QtWidgets.QPushButton(self.central_widget)
        self.task1.setObjectName("task1")
        self.task_selection.addWidget(self.task1)
        self.task2 = QtWidgets.QPushButton(self.central_widget)
        self.task2.setObjectName("task2")
        self.task_selection.addWidget(self.task2)
        self.task3 = QtWidgets.QPushButton(self.central_widget)
        self.task3.setObjectName("task3")
        self.task_selection.addWidget(self.task3)
        self.task4 = QtWidgets.QPushButton(self.central_widget)
        self.task4.setObjectName("task4")
        self.task_selection.addWidget(self.task4)
        self.task5 = QtWidgets.QPushButton(self.central_widget)
        self.task5.setObjectName("task5")
        self.task_selection.addWidget(self.task5)
        self.task6 = QtWidgets.QPushButton(self.central_widget)
        self.task6.setObjectName("task6")
        self.task_selection.addWidget(self.task6)
        self.task7 = QtWidgets.QPushButton(self.central_widget)
        self.task7.setObjectName("task7")
        self.task_selection.addWidget(self.task7)

        self.right_layout.addLayout(self.task_selection)
        self.cli_layout = QtWidgets.QVBoxLayout()
        self.cli_layout.setObjectName("cli_layout")

        self.cli_display = QtWidgets.QTextBrowser(self.central_widget)
        self.cli_display.setObjectName("cli_display")

        # embed xterm into widget
        # self.process = QtCore.QProcess(self.central_widget)
        # self.cli_display = QtWidgets.QWidget(self.central_widget)
        # self.cli_display.setObjectName("cli_display")
        # self.process.start('xterm', ['-into', str(self.cli_display.winId())])
        # print(str(self.cli_display.winId()))

        self.cli_layout.addWidget(self.cli_display)
        self.line_edit = QtWidgets.QLineEdit(self.central_widget)
        self.line_edit.setObjectName("line_edit")
        self.cli_layout.addWidget(self.line_edit)
        self.right_layout.addLayout(self.cli_layout)
        self.horizontalLayout.addLayout(self.right_layout)
        MainWindow.setCentralWidget(self.central_widget)

        # Connect Signal to Methods

        self.retranslateUi(MainWindow)
        # self.task0.clicked.connect(self.line_edit.paste)
        # self.task1.clicked.connect(self.line_edit.copy)
        # self.is_auto_checkbox.stateChanged['int'].connect(self.line_edit.paste)
        self.line_edit.returnPressed.connect(self.read_line)
        # self.camera0.clicked.connect(self.display0.update)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def read_line(self):
        self.cli_display.append(self.line_edit.text())
        self.line_edit.clear()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Robosub GUI"))
        self.camera0.setText(_translate("MainWindow", "camera 0"))
        self.camera1.setText(_translate("MainWindow", "camera 1"))
        self.camera2.setText(_translate("MainWindow", "camera 2"))
        self.load_default_button.setText(_translate("MainWindow", "Load Default Params"))
        self.is_auto_checkbox.setText(_translate("MainWindow", "Auto mode"))
        self.task0.setText(_translate("MainWindow", "task 0"))
        self.task1.setText(_translate("MainWindow", "task 1"))
        self.task2.setText(_translate("MainWindow", "task 2"))
        self.task3.setText(_translate("MainWindow", "task 3"))
        self.task4.setText(_translate("MainWindow", "task 4"))
        self.task5.setText(_translate("MainWindow", "task 5"))
        self.task6.setText(_translate("MainWindow", "task 6"))
        self.task7.setText(_translate("MainWindow", "task 7"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

