set(_CATKIN_CURRENT_PACKAGE "ez_async_data")
set(ez_async_data_VERSION "0.0.0")
set(ez_async_data_MAINTAINER "blah <blah@todo.todo>")
set(ez_async_data_PACKAGE_FORMAT "1")
set(ez_async_data_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "message_generation")
set(ez_async_data_BUILD_EXPORT_DEPENDS "message_runtime" "roscpp" "rospy" "std_msgs")
set(ez_async_data_BUILDTOOL_DEPENDS "catkin")
set(ez_async_data_BUILDTOOL_EXPORT_DEPENDS )
set(ez_async_data_EXEC_DEPENDS "message_runtime" "roscpp" "rospy" "std_msgs")
set(ez_async_data_RUN_DEPENDS "message_runtime" "roscpp" "rospy" "std_msgs")
set(ez_async_data_TEST_DEPENDS )
set(ez_async_data_DOC_DEPENDS )
set(ez_async_data_URL_WEBSITE "")
set(ez_async_data_URL_BUGTRACKER "")
set(ez_async_data_URL_REPOSITORY "")
set(ez_async_data_DEPRECATED "")